name: tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'cmake_helpers'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'cmake_helpers'
  workflow_dispatch:

jobs:
  build:
    uses: phisko/cmake-cxx-vcpkg/.github/workflows/build.yml@main
    with:
      cmake_options: -DPUTILS_META_TESTS=ON
      vcpkg_commit: '223d33be7d3ec6c3d64381ca37f501b8c87dda6a'
