name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows ]
        configuration: [ Release, Debug ]

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: phisko/cmake-cxx-conan/.github/workflows/test.yml@main
        with:
          os: ${{ matrix.os }}
          cmake_options: -DPUTILS_META_TESTS=ON
