name: gcc

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'cmake_helpers'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'cmake_helpers'
  workflow_dispatch:

jobs:
  debug:
    uses: phisko/cmake-cxx-conan/.github/workflows/test.yml@main
    with:
      os: ubuntu-latest
      configuration: Debug
      cmake_options: -DPUTILS_META_TESTS=ON

  release:
    uses: phisko/cmake-cxx-conan/.github/workflows/test.yml@main
    with:
      os: ubuntu-latest
      configuration: Release
      cmake_options: -DPUTILS_META_TESTS=ON
